//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kabinet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int ID { get; set; }
        public int ProductID { get; set; }
        public int UserID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Comments { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int Quantity { get; set; }
        public Nullable<decimal> Summ { get; set; }
        public bool IsPayed { get; set; }
        public Nullable<System.DateTime> PatedDate { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Users Users { get; set; }
    }
}
